/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package addressBook;

import addressBook.Contact;
import java.util.ArrayList;
/**
 *
 * @author eoin0
 */
public class ABGUI extends javax.swing.JFrame {

    ArrayList<Contact> clist;
    /**
     * Creates new form ABGUI
     */
    public ABGUI() {
        initComponents();
        clist = new ArrayList<>();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstnameTF = new javax.swing.JTextField();
        lastnameTF = new javax.swing.JTextField();
        phoneTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTA = new javax.swing.JTextArea();
        firstnameLBL = new javax.swing.JLabel();
        lastnameLBL = new javax.swing.JLabel();
        phoneLBL = new javax.swing.JLabel();
        emailLBL = new javax.swing.JLabel();
        addressLBL = new javax.swing.JLabel();
        addBTN = new javax.swing.JButton();
        displayBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        clearBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        firstnameTF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(firstnameTF);
        firstnameTF.setBounds(1120, 220, 234, 38);

        lastnameTF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(lastnameTF);
        lastnameTF.setBounds(1120, 300, 234, 38);

        phoneTF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(phoneTF);
        phoneTF.setBounds(1120, 390, 234, 38);

        emailTF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(emailTF);
        emailTF.setBounds(1120, 470, 234, 38);

        addressTA.setColumns(20);
        addressTA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        addressTA.setRows(5);
        jScrollPane1.setViewportView(addressTA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(1120, 570, 434, 166);

        firstnameLBL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        firstnameLBL.setText("Firstname");
        getContentPane().add(firstnameLBL);
        firstnameLBL.setBounds(1010, 210, 104, 32);

        lastnameLBL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lastnameLBL.setText("Lastname");
        getContentPane().add(lastnameLBL);
        lastnameLBL.setBounds(1010, 290, 101, 32);

        phoneLBL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        phoneLBL.setText("Phone");
        getContentPane().add(phoneLBL);
        phoneLBL.setBounds(1030, 380, 68, 32);

        emailLBL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        emailLBL.setText("Email");
        getContentPane().add(emailLBL);
        emailLBL.setBounds(1030, 460, 57, 32);

        addressLBL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        addressLBL.setText("Address");
        getContentPane().add(addressLBL);
        addressLBL.setBounds(1020, 560, 90, 30);

        addBTN.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });
        getContentPane().add(addBTN);
        addBTN.setBounds(740, 820, 140, 70);

        displayBTN.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        displayBTN.setText("Display");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });
        getContentPane().add(displayBTN);
        displayBTN.setBounds(880, 820, 140, 70);

        exitBTN.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });
        getContentPane().add(exitBTN);
        exitBTN.setBounds(1020, 820, 140, 70);

        displayTA.setColumns(20);
        displayTA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        displayTA.setRows(5);
        jScrollPane2.setViewportView(displayTA);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(450, 210, 510, 560);

        clearBTN.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        clearBTN.setText("Clear");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });
        getContentPane().add(clearBTN);
        clearBTN.setBounds(1160, 820, 140, 70);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Contact Keeper");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(790, 30, 370, 150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        
        Contact tempC = new Contact();

        tempC.firstname = firstnameTF.getText();
        tempC.lastname = lastnameTF.getText();
        tempC.phone = phoneTF.getText();
        tempC.email = emailTF.getText();
        tempC.address = addressTA.getText();
        
        displayTA.setText("Contact added");
        clist.add(tempC);
        clear();
        
    }//GEN-LAST:event_addBTNActionPerformed

    private void clear(){
        firstnameTF.setText("");
        lastnameTF.setText("");
        phoneTF.setText("");
        emailTF.setText("");
        addressTA.setText("");
    }
    
    
    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
        // TODO add your handling code here:
        if(clist.isEmpty()){
            displayTA.setText("You've no friends.");
        }else{
            Contact temp;
            for( int i = 0; i < clist.size(); i++){
                temp = clist.get(i);
                displayTA.append("\n"+temp.toString());
            }
        }
    }//GEN-LAST:event_displayBTNActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JLabel addressLBL;
    private javax.swing.JTextArea addressTA;
    private javax.swing.JButton clearBTN;
    private javax.swing.JButton displayBTN;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JLabel emailLBL;
    private javax.swing.JTextField emailTF;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel firstnameLBL;
    private javax.swing.JTextField firstnameTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lastnameLBL;
    private javax.swing.JTextField lastnameTF;
    private javax.swing.JLabel phoneLBL;
    private javax.swing.JTextField phoneTF;
    // End of variables declaration//GEN-END:variables
}
